package pl.example.model;

import java.util.HashMap;
import java.util.Map;

public class CountryDecoder {

    private static final Map<String,String> countryMapInPolish = new HashMap<>();
    private static final Map<String,String> countryMapInEnglish = new HashMap<>();

    static {
        countryMapInPolish.put("AF", "Afganistan");
        countryMapInPolish.put("AL", "Albania");
        countryMapInPolish.put("DZ", "Algieria");
        countryMapInPolish.put("AD", "Andora");
        countryMapInPolish.put("AO", "Angola");
        countryMapInPolish.put("AI", "Anguilla");
        countryMapInPolish.put("AQ", "Antarktyda");
        countryMapInPolish.put("AG", "Antigua i Barbuda");
        countryMapInPolish.put("SA", "Arabia Saudyjska");
        countryMapInPolish.put("AR", "Argentyna");
        countryMapInPolish.put("AM", "Armenia");
        countryMapInPolish.put("AW", "Aruba");
        countryMapInPolish.put("AU", "Australia");
        countryMapInPolish.put("AT", "Austria");
        countryMapInPolish.put("AZ", "Azerbejdżan");
        countryMapInPolish.put("BS", "Bahamy");
        countryMapInPolish.put("BH", "Bahrajn");
        countryMapInPolish.put("BD", "Bangladesz");
        countryMapInPolish.put("BB", "Barbados");
        countryMapInPolish.put("BY", "Białoruś");
        countryMapInPolish.put("BE", "Belgia");
        countryMapInPolish.put("BZ", "Belize");
        countryMapInPolish.put("BJ", "Benin");
        countryMapInPolish.put("BM", "Bermudy");
        countryMapInPolish.put("BT", "Bhutan");
        countryMapInPolish.put("BO", "Boliwia");
        countryMapInPolish.put("BA", "Bośnia i Hercegowina");
        countryMapInPolish.put("BW", "Botswana");
        countryMapInPolish.put("BR", "Brazylia");
        countryMapInPolish.put("BN", "Brunei Darussalam");
        countryMapInPolish.put("IO", "Brytyjskie Terytorium Oceanu Indyjskiego");
        countryMapInPolish.put("BG", "Bułgaria");
        countryMapInPolish.put("BF", "Burkina Faso");
        countryMapInPolish.put("BI", "Burundi");
        countryMapInPolish.put("XC", "Ceuta");
        countryMapInPolish.put("CL", "Chile");
        countryMapInPolish.put("CN", "Chiny");
        countryMapInPolish.put("CW", "Curaçao");
        countryMapInPolish.put("HR", "Chorwacja");
        countryMapInPolish.put("CY", "Cypr");
        countryMapInPolish.put("TD", "Czad");
        countryMapInPolish.put("ME", "Czarnogóra");
        countryMapInPolish.put("CZ", "Czechy");
        countryMapInPolish.put("DK", "Dania");
        countryMapInPolish.put("DM", "Dominika");
        countryMapInPolish.put("DO", "Dominikana");
        countryMapInPolish.put("DJ", "Dżibuti");
        countryMapInPolish.put("EG", "Egipt");
        countryMapInPolish.put("EC", "Ekwador");
        countryMapInPolish.put("ER", "Erytrea");
        countryMapInPolish.put("EE", "Estonia");
        countryMapInPolish.put("ET", "Etiopia");
        countryMapInPolish.put("FK", "Falklandy");
        countryMapInPolish.put("FJ", "Fidżi Republika");
        countryMapInPolish.put("PH", "Filipiny");
        countryMapInPolish.put("FI", "Finlandia");
        countryMapInPolish.put("TF", "Francuskie Terytorium Południowe");
        countryMapInPolish.put("FR", "Francja");
        countryMapInPolish.put("GA", "Gabon");
        countryMapInPolish.put("GM", "Gambia");
        countryMapInPolish.put("GH", "Ghana");
        countryMapInPolish.put("GI", "Gibraltar");
        countryMapInPolish.put("GR", "Grecja");
        countryMapInPolish.put("GD", "Grenada");
        countryMapInPolish.put("GL", "Grenlandia");
        countryMapInPolish.put("GE", "Gruzja");
        countryMapInPolish.put("GU", "Guam");
        countryMapInPolish.put("GY", "Gujana");
        countryMapInPolish.put("GT", "Gwatemala");
        countryMapInPolish.put("GN", "Gwinea");
        countryMapInPolish.put("GQ", "Gwinea Równikowa");
        countryMapInPolish.put("GW", "Gwinea-Bissau");
        countryMapInPolish.put("HT", "Haiti");
        countryMapInPolish.put("ES", "Hiszpania");
        countryMapInPolish.put("HN", "Honduras");
        countryMapInPolish.put("HK", "Hongkong");
        countryMapInPolish.put("IN", "Indie");
        countryMapInPolish.put("ID", "Indonezja");
        countryMapInPolish.put("IQ", "Irak");
        countryMapInPolish.put("IR", "Iran");
        countryMapInPolish.put("IE", "Irlandia");
        countryMapInPolish.put("IS", "Islandia");
        countryMapInPolish.put("IL", "Izrael");
        countryMapInPolish.put("JM", "Jamajka");
        countryMapInPolish.put("JP", "Japonia");
        countryMapInPolish.put("YE", "Jemen");
        countryMapInPolish.put("JO", "Jordania");
        countryMapInPolish.put("KY", "Kajmany");
        countryMapInPolish.put("KH", "Kambodża");
        countryMapInPolish.put("CM", "Kamerun");
        countryMapInPolish.put("CA", "Kanada");
        countryMapInPolish.put("QA", "Katar");
        countryMapInPolish.put("KZ", "Kazachstan");
        countryMapInPolish.put("KE", "Kenia");
        countryMapInPolish.put("KG", "Kirgistan");
        countryMapInPolish.put("KI", "Kiribati");
        countryMapInPolish.put("CO", "Kolumbia");
        countryMapInPolish.put("KM", "Komory");
        countryMapInPolish.put("CG", "Kongo");
        countryMapInPolish.put("CD", "Kongo, Republika Demokratyczna");
        countryMapInPolish.put("KP", "Koreańska Republika Ludowo-Demokratyczna");
        countryMapInPolish.put("XK", "Kosowo");
        countryMapInPolish.put("CR", "Kostaryka");
        countryMapInPolish.put("CU", "Kuba");
        countryMapInPolish.put("KW", "Kuwejt");
        countryMapInPolish.put("LA", "Laos");
        countryMapInPolish.put("LS", "Lesotho");
        countryMapInPolish.put("LB", "Liban");
        countryMapInPolish.put("LR", "Liberia");
        countryMapInPolish.put("LY", "Libia");
        countryMapInPolish.put("LI", "Liechtenstein");
        countryMapInPolish.put("LT", "Litwa");
        countryMapInPolish.put("LU", "Luksemburg");
        countryMapInPolish.put("LV", "Łotwa");
        countryMapInPolish.put("MK", "Macedonia Północna");
        countryMapInPolish.put("MG", "Madagaskar");
        countryMapInPolish.put("YT", "Majotta");
        countryMapInPolish.put("MO", "Makau");
        countryMapInPolish.put("MW", "Malawi");
        countryMapInPolish.put("MV", "Malediwy");
        countryMapInPolish.put("MY", "Malezja");
        countryMapInPolish.put("ML", "Mali");
        countryMapInPolish.put("MT", "Malta");
        countryMapInPolish.put("MP", "Mariany Północne");
        countryMapInPolish.put("MA", "Maroko");
        countryMapInPolish.put("MR", "Mauretania");
        countryMapInPolish.put("MU", "Mauritius");
        countryMapInPolish.put("MX", "Meksyk");
        countryMapInPolish.put("XL", "Melilla");
        countryMapInPolish.put("FM", "Mikronezja");
        countryMapInPolish.put("UM", "Minor (Powiernicze Wyspy Pacyfiku Stanów Zjednoczonych)");
        countryMapInPolish.put("MD", "Mołdawia");
        countryMapInPolish.put("MN", "Mongolia");
        countryMapInPolish.put("MS", "Montserrat");
        countryMapInPolish.put("MZ", "Mozambik");
        countryMapInPolish.put("MM", "Myanmar (Burma)");
        countryMapInPolish.put("NA", "Namibia");
        countryMapInPolish.put("NR", "Nauru");
        countryMapInPolish.put("NP", "Nepal");
        countryMapInPolish.put("NL", "Niderlandy");
        countryMapInPolish.put("DE", "Niemcy");
        countryMapInPolish.put("NE", "Niger");
        countryMapInPolish.put("NG", "Nigeria");
        countryMapInPolish.put("NI", "Nikaragua");
        countryMapInPolish.put("NU", "Niue");
        countryMapInPolish.put("NF", "Norfolk");
        countryMapInPolish.put("NO", "Norwegia");
        countryMapInPolish.put("NC", "Nowa Kaledonia");
        countryMapInPolish.put("NZ", "Nowa Zelandia");
        countryMapInPolish.put("PS", "Okupowane Terytorium Palestyny");
        countryMapInPolish.put("OM", "Oman");
        countryMapInPolish.put("PK", "Pakistan");
        countryMapInPolish.put("PW", "Palau");
        countryMapInPolish.put("PA", "Panama");
        countryMapInPolish.put("PG", "Papua Nowa Gwinea");
        countryMapInPolish.put("PY", "Paragwaj");
        countryMapInPolish.put("PE", "Peru");
        countryMapInPolish.put("PN", "Pitcairn");
        countryMapInPolish.put("PF", "Polinezja Francuska");
        countryMapInPolish.put("PL", "Polska");
        countryMapInPolish.put("ZA", "Południowa Afryka");
        countryMapInPolish.put("GS", "Południowa Georgia i Południowe Wyspy Sandwich");
        countryMapInPolish.put("PT", "Portugalia");
        countryMapInPolish.put("KR", "Republika Korei");
        countryMapInPolish.put("CF", "Rep.Środkowoafryańska");
        countryMapInPolish.put("RU", "Rosja");
        countryMapInPolish.put("RW", "Rwanda");
        countryMapInPolish.put("EH", "Sahara Zachodnia");
        countryMapInPolish.put("BL", "Saint Barthelemy");
        countryMapInPolish.put("RO", "Rumunia");
        countryMapInPolish.put("SV", "Salwador");
        countryMapInPolish.put("WS", "Samoa");
        countryMapInPolish.put("AS", "Samoa Amerykańskie");
        countryMapInPolish.put("SM", "San Marino");
        countryMapInPolish.put("SN", "Senegal");
        countryMapInPolish.put("XS", "Serbia");
        countryMapInPolish.put("SC", "Seszele");
        countryMapInPolish.put("SL", "Sierra Leone");
        countryMapInPolish.put("SG", "Singapur");
        countryMapInPolish.put("SZ", "Suazi");
        countryMapInPolish.put("SK", "Słowacja");
        countryMapInPolish.put("SI", "Słowenia");
        countryMapInPolish.put("SO", "Somalia");
        countryMapInPolish.put("LK", "Sri Lanka");
        countryMapInPolish.put("PM", "St. Pierre i Miquelon");
        countryMapInPolish.put("KN", "St.Kitts i Nevis");
        countryMapInPolish.put("LC", "St.Lucia");
        countryMapInPolish.put("VC", "St.Vincent i Grenadyny");
        countryMapInPolish.put("US", "Stany Zjedn. Ameryki");
        countryMapInPolish.put("SD", "Sudan");
        countryMapInPolish.put("SS", "Sudan Południowy");
        countryMapInPolish.put("SR", "Surinam");
        countryMapInPolish.put("SY", "Syria");
        countryMapInPolish.put("CH", "Szwajcaria");
        countryMapInPolish.put("SE", "Szwecja");
        countryMapInPolish.put("SH", "Święta Helena");
        countryMapInPolish.put("TJ", "Tadżykistan");
        countryMapInPolish.put("TH", "Tajlandia");
        countryMapInPolish.put("TW", "Tajwan");
        countryMapInPolish.put("TZ", "Tanzania");
        countryMapInPolish.put("TG", "Togo");
        countryMapInPolish.put("TK", "Tokelau");
        countryMapInPolish.put("TO", "Tonga");
        countryMapInPolish.put("TT", "Trynidad i Tobago");
        countryMapInPolish.put("TN", "Tunezja");
        countryMapInPolish.put("TR", "Turcja");
        countryMapInPolish.put("TM", "Turkmenistan");
        countryMapInPolish.put("TC", "Wyspy Turks i Caicos");
        countryMapInPolish.put("TV", "Tuvalu");
        countryMapInPolish.put("UG", "Uganda");
        countryMapInPolish.put("UA", "Ukraina");
        countryMapInPolish.put("UY", "Urugwaj");
        countryMapInPolish.put("UZ", "Uzbekistan");
        countryMapInPolish.put("VU", "Vanuatu");
        countryMapInPolish.put("WF", "Wallis i Futuna");
        countryMapInPolish.put("VA", "Watykan");
        countryMapInPolish.put("VE", "Wenezuela");
        countryMapInPolish.put("HU", "Węgry");
        countryMapInPolish.put("GB", "Wielka Brytania");
        countryMapInPolish.put("VN", "Wietnam");
        countryMapInPolish.put("IT", "Włochy");
        countryMapInPolish.put("TL", "Wschodni Timor");
        countryMapInPolish.put("CI", "Wyb.Kości Słoniowej");
        countryMapInPolish.put("BV", "Wyspa Bouveta");
        countryMapInPolish.put("CX", "Wyspa Bożego Narodzenia");
        countryMapInPolish.put("CK", "Wyspy Cooka");
        countryMapInPolish.put("VI", "Wyspy Dziewicze-USA");
        countryMapInPolish.put("VG", "Wyspy Dziewicze-W.B");
        countryMapInPolish.put("HM", "Wyspy Heard i McDonald");
        countryMapInPolish.put("CC", "Wyspy Kokosowe (Keelinga)");
        countryMapInPolish.put("FO", "Wyspy Owcze");
        countryMapInPolish.put("MH", "Wyspy Marshalla");
        countryMapInPolish.put("SB", "Wyspy Salomona");
        countryMapInPolish.put("SX", "Wyspa Sint Maarten (część holenderska wyspy)");
        countryMapInPolish.put("ST", "Wyspy Św.Tomasza i Książęca");
        countryMapInPolish.put("ZM", "Zambia");
        countryMapInPolish.put("ZW", "Zimbabwe");
        countryMapInPolish.put("AE", "Zjedn.Emiraty Arabskie");
        countryMapInPolish.put("XI", "Zjednoczone Królestwo (Irlandia Północna)");
    }

    static {
        countryMapInEnglish.put("AF", "Afghanistan");
        countryMapInEnglish.put("AL", "Albania");
        countryMapInEnglish.put("DZ", "Algeria");
        countryMapInEnglish.put("AD", "Andorra");
        countryMapInEnglish.put("AO", "Angola");
        countryMapInEnglish.put("AI", "Anguilla");
        countryMapInEnglish.put("AQ", "Antarctica");
        countryMapInEnglish.put("AG", "Antigua and Barbuda");
        countryMapInEnglish.put("SA", "Saudi Arabia");
        countryMapInEnglish.put("AR", "Argentina");
        countryMapInEnglish.put("AM", "Armenia");
        countryMapInEnglish.put("AW", "Aruba");
        countryMapInEnglish.put("AU", "Australia");
        countryMapInEnglish.put("AT", "Austria");
        countryMapInEnglish.put("AZ", "Azerbaijan");
        countryMapInEnglish.put("BS", "Bahamas");
        countryMapInEnglish.put("BH", "Bahrain");
        countryMapInEnglish.put("BD", "Bangladesh");
        countryMapInEnglish.put("BB", "Barbados");
        countryMapInEnglish.put("BY", "Belarus");
        countryMapInEnglish.put("BE", "Belgium");
        countryMapInEnglish.put("BZ", "Belize");
        countryMapInEnglish.put("BJ", "Benin");
        countryMapInEnglish.put("BM", "Bermuda");
        countryMapInEnglish.put("BT", "Bhutan");
        countryMapInEnglish.put("BO", "Bolivia");
        countryMapInEnglish.put("BA", "Bosnia and Herzegovina");
        countryMapInEnglish.put("BW", "Botswana");
        countryMapInEnglish.put("BR", "Brazil");
        countryMapInEnglish.put("BN", "Brunei Darussalam");
        countryMapInEnglish.put("IO", "British Indian Ocean Territory");
        countryMapInEnglish.put("BG", "Bulgaria");
        countryMapInEnglish.put("BF", "Burkina Faso");
        countryMapInEnglish.put("BI", "Burundi");
        countryMapInEnglish.put("XC", "Ceuta");
        countryMapInEnglish.put("CL", "Chile");
        countryMapInEnglish.put("CN", "China");
        countryMapInEnglish.put("CW", "Curaçao");
        countryMapInEnglish.put("HR", "Croatia");
        countryMapInEnglish.put("CY", "Cyprus");
        countryMapInEnglish.put("TD", "Chad");
        countryMapInEnglish.put("ME", "Montenegro");
        countryMapInEnglish.put("CZ", "Czechia");
        countryMapInEnglish.put("DK", "Denmark");
        countryMapInEnglish.put("DM", "Dominica");
        countryMapInEnglish.put("DO", "Dominican Republic");
        countryMapInEnglish.put("DJ", "Djibouti");
        countryMapInEnglish.put("EG", "Egypt");
        countryMapInEnglish.put("EC", "Ecuador");
        countryMapInEnglish.put("ER", "Eritrea");
        countryMapInEnglish.put("EE", "Estonia");
        countryMapInEnglish.put("ET", "Ethiopia");
        countryMapInEnglish.put("FK", "Falkland Islands (Malvinas)");
        countryMapInEnglish.put("FJ", "Fiji");
        countryMapInEnglish.put("PH", "Philippines");
        countryMapInEnglish.put("FI", "Finland");
        countryMapInEnglish.put("TF", "French Southern Territories");
        countryMapInEnglish.put("FR", "France");
        countryMapInEnglish.put("GA", "Gabon");
        countryMapInEnglish.put("GM", "Gambia");
        countryMapInEnglish.put("GH", "Ghana");
        countryMapInEnglish.put("GI", "Gibraltar");
        countryMapInEnglish.put("GR", "Greece");
        countryMapInEnglish.put("GD", "Grenada");
        countryMapInEnglish.put("GL", "Greenland");
        countryMapInEnglish.put("GE", "Georgia");
        countryMapInEnglish.put("GU", "Guam");
        countryMapInEnglish.put("GY", "Guyana");
        countryMapInEnglish.put("GT", "Guatemala");
        countryMapInEnglish.put("GN", "Guinea");
        countryMapInEnglish.put("GQ", "Equatorial Guinea");
        countryMapInEnglish.put("GW", "Guinea-Bissau");
        countryMapInEnglish.put("HT", "Haiti");
        countryMapInEnglish.put("ES", "Spain");
        countryMapInEnglish.put("HN", "Honduras");
        countryMapInEnglish.put("HK", "Hong Kong");
        countryMapInEnglish.put("IN", "India");
        countryMapInEnglish.put("ID", "Indonesia");
        countryMapInEnglish.put("IQ", "Iraq");
        countryMapInEnglish.put("IR", "Iran, Islamic Republic of");
        countryMapInEnglish.put("IE", "Ireland");
        countryMapInEnglish.put("IS", "Iceland");
        countryMapInEnglish.put("IL", "Israel");
        countryMapInEnglish.put("JM", "Jamaica");
        countryMapInEnglish.put("JP", "Japan");
        countryMapInEnglish.put("YE", "Yemen");
        countryMapInEnglish.put("JO", "Jordan");
        countryMapInEnglish.put("KY", "Cayman Islands");
        countryMapInEnglish.put("KH", "Cambodia");
        countryMapInEnglish.put("CM", "Cameroon");
        countryMapInEnglish.put("CA", "Canada");
        countryMapInEnglish.put("QA", "Qatar");
        countryMapInEnglish.put("KZ", "Kazakhstan");
        countryMapInEnglish.put("KE", "Kenya");
        countryMapInEnglish.put("KG", "Kyrgyzstan");
        countryMapInEnglish.put("KI", "Kiribati");
        countryMapInEnglish.put("CO", "Colombia");
        countryMapInEnglish.put("KM", "Comoros");
        countryMapInEnglish.put("CG", "Congo");
        countryMapInEnglish.put("CD", "Congo, Democratic Republic of the");
        countryMapInEnglish.put("KP", "Korea, Democratic People's Republic of");
        countryMapInEnglish.put("XK", "Kosovo");
        countryMapInEnglish.put("CR", "Costa Rica");
        countryMapInEnglish.put("CU", "Cuba");
        countryMapInEnglish.put("KW", "Kuwait");
        countryMapInEnglish.put("LA", "Lao People's Democratic Republic");
        countryMapInEnglish.put("LS", "Lesotho");
        countryMapInEnglish.put("LB", "Lebanon");
        countryMapInEnglish.put("LR", "Liberia");
        countryMapInEnglish.put("LY", "Libya");
        countryMapInEnglish.put("LI", "Liechtenstein");
        countryMapInEnglish.put("LT", "Lithuania");
        countryMapInEnglish.put("LU", "Luxembourg");
        countryMapInEnglish.put("LV", "Latvia");
        countryMapInEnglish.put("MK", "North Macedonia");
        countryMapInEnglish.put("MG", "Madagascar");
        countryMapInEnglish.put("YT", "Mayotte");
        countryMapInEnglish.put("MO", "Macao");
        countryMapInEnglish.put("MW", "Malawi");
        countryMapInEnglish.put("MV", "Maldives");
        countryMapInEnglish.put("MY", "Malaysia");
        countryMapInEnglish.put("ML", "Mali");
        countryMapInEnglish.put("MT", "Malta");
        countryMapInEnglish.put("MP", "Northern Mariana Islands");
        countryMapInEnglish.put("MA", "Morocco");
        countryMapInEnglish.put("MR", "Mauritania");
        countryMapInEnglish.put("MU", "Mauritius");
        countryMapInEnglish.put("MX", "Mexico");
        countryMapInEnglish.put("XL", "Melilla");
        countryMapInEnglish.put("FM", "Micronesia, Federal States of");
        countryMapInEnglish.put("UM", "U.S. Minor Outlying Islands");
        countryMapInEnglish.put("MD", "Moldova, Republic of");
        countryMapInEnglish.put("MN", "Mongolia");
        countryMapInEnglish.put("MS", "Montserrat");
        countryMapInEnglish.put("MZ", "Mozambique");
        countryMapInEnglish.put("MM", "Myanmar");
        countryMapInEnglish.put("NA", "Namibia");
        countryMapInEnglish.put("NR", "Nauru");
        countryMapInEnglish.put("NP", "Nepal");
        countryMapInEnglish.put("NL", "Netherlands");
        countryMapInEnglish.put("DE", "Germany");
        countryMapInEnglish.put("NE", "Niger");
        countryMapInEnglish.put("NG", "Nigeria");
        countryMapInEnglish.put("NI", "Nicaragua");
        countryMapInEnglish.put("NU", "Niue");
        countryMapInEnglish.put("NF", "Norfolk Island");
        countryMapInEnglish.put("NO", "Norway");
        countryMapInEnglish.put("NC", "New Caledonia");
        countryMapInEnglish.put("NZ", "New Zealand");
        countryMapInEnglish.put("PS", "Palestinian Territory, Occupied");
        countryMapInEnglish.put("OM", "Oman");
        countryMapInEnglish.put("PK", "Pakistan");
        countryMapInEnglish.put("PW", "Palau");
        countryMapInEnglish.put("PA", "Panama");
        countryMapInEnglish.put("PG", "Papua New Guinea");
        countryMapInEnglish.put("PY", "Paraguay");
        countryMapInEnglish.put("PE", "Peru");
        countryMapInEnglish.put("PN", "Pitcairn");
        countryMapInEnglish.put("PF", "French Polynesia");
        countryMapInEnglish.put("PL", "Poland");
        countryMapInEnglish.put("ZA", "South Africa");
        countryMapInEnglish.put("GS", "South Georgia and the South Sandwich Islands");
        countryMapInEnglish.put("PT", "Portugal");
        countryMapInEnglish.put("KR", "Korea, Republic of");
        countryMapInEnglish.put("CF", "Central African Republic");
        countryMapInEnglish.put("RU", "Russian Federation");
        countryMapInEnglish.put("RW", "Rwanda");
        countryMapInEnglish.put("EH", "Western Sahara");
        countryMapInEnglish.put("BL", "Saint Barthelemy");
        countryMapInEnglish.put("RO", "Romania");
        countryMapInEnglish.put("SV", "El Salvador");
        countryMapInEnglish.put("WS", "Samoa");
        countryMapInEnglish.put("AS", "American Samoa");
        countryMapInEnglish.put("SM", "San Marino");
        countryMapInEnglish.put("SN", "Senegal");
        countryMapInEnglish.put("XS", "Serbia");
        countryMapInEnglish.put("SC", "Seychelles");
        countryMapInEnglish.put("SL", "Sierra Leone");
        countryMapInEnglish.put("SG", "Singapore");
        countryMapInEnglish.put("SZ", "Swaziland");
        countryMapInEnglish.put("SK", "Slovakia");
        countryMapInEnglish.put("SI", "Slovenia");
        countryMapInEnglish.put("SO", "Somalia");
        countryMapInEnglish.put("LK", "Sri Lanka");
        countryMapInEnglish.put("PM", "St. Pierre and Miquelon");
        countryMapInEnglish.put("KN", "St. Kitts and Nevis");
        countryMapInEnglish.put("LC", "St. Lucia");
        countryMapInEnglish.put("VC", "St. Vincent and the Grenadines");
        countryMapInEnglish.put("US", "United States of America");
        countryMapInEnglish.put("SD", "Sudan");
        countryMapInEnglish.put("SS", "South Sudan");
        countryMapInEnglish.put("SR", "Suriname");
        countryMapInEnglish.put("SY", "Syrian Arab Republic");
        countryMapInEnglish.put("CH", "Switzerland");
        countryMapInEnglish.put("SE", "Sweden");
        countryMapInEnglish.put("SH", "St. Helena");
        countryMapInEnglish.put("TJ", "Tajikistan");
        countryMapInEnglish.put("TH", "Thailand");
        countryMapInEnglish.put("TW", "Taiwan, Province of China");
        countryMapInEnglish.put("TZ", "Tanzania, United Republic of");
        countryMapInEnglish.put("TG", "Togo");
        countryMapInEnglish.put("TK", "Tokelau");
        countryMapInEnglish.put("TO", "Tonga");
        countryMapInEnglish.put("TT", "Trinidad and Tobago");
        countryMapInEnglish.put("TN", "Tunisia");
        countryMapInEnglish.put("TR", "Turkey");
        countryMapInEnglish.put("TM", "Turkmenistan");
        countryMapInEnglish.put("TC", "Turks and Caicos Islands");
        countryMapInEnglish.put("TV", "Tuvalu");
        countryMapInEnglish.put("UG", "Uganda");
        countryMapInEnglish.put("UA", "Ukraine");
        countryMapInEnglish.put("UY", "Uruguay");
        countryMapInEnglish.put("UZ", "Uzbekistan");
        countryMapInEnglish.put("VU", "Vanuatu");
        countryMapInEnglish.put("WF", "Wallis and Futuna Islands");
        countryMapInEnglish.put("VA", "Holy See (Vatican City State)");
        countryMapInEnglish.put("VE", "Venezuela");
        countryMapInEnglish.put("HU", "Hungary");
        countryMapInEnglish.put("GB", "United Kingdom");
        countryMapInEnglish.put("VN", "Viet Nam");
        countryMapInEnglish.put("IT", "Italy");
        countryMapInEnglish.put("TL", "Timor-Leste");
        countryMapInEnglish.put("CI", "Côte d'Ivoire");
        countryMapInEnglish.put("BV", "Bouvet Island");
        countryMapInEnglish.put("CX", "Christmas Island");
        countryMapInEnglish.put("CC", "Cocos (Keeling) Islands");
        countryMapInEnglish.put("FO", "Faroe Islands");
        countryMapInEnglish.put("MH", "Marshall Islands");
        countryMapInEnglish.put("SB", "Solomon Islands");
        countryMapInEnglish.put("SX", "Sint Maarten (Dutch part)");
        countryMapInEnglish.put("ST", "Sao Tome and Principe");
        countryMapInEnglish.put("ZM", "Zambia");
        countryMapInEnglish.put("QR", "Stores and provisions within the framework of intra-EU trade");
        countryMapInEnglish.put("CV", "Cape Verde");
        countryMapInEnglish.put("ZW", "Zimbabwe");
        countryMapInEnglish.put("AE", "United Arab Emirates");
        countryMapInEnglish.put("XI", "United Kingdom (Northern Ireland)");
    }

    public static String getFullNameOfCountry(String countryCode){
        return countryMapInEnglish.getOrDefault(countryCode, "Nieznany kraj!");
    }
}
